Fix duplicate base URL in request to Bitbucket Server
Commit e4d32d549b3bf29a896ae0ec31f2d88cbcb32377 (for JENKINS-64418)
introduced a bug that duplicates the base URL in some HTTP requests
to Bitbucket Server, causing an error like this:

java.io.FileNotFoundException: URL: https://bitbucket.examplehttps://bitbucket.example/rest/api/1.0/projects/DEMO/repos/demo/branches?filterText=master&start=0&limit=200
	at com.cloudbees.jenkins.plugins.bitbucket.impl.client.AbstractBitbucketApi.doRequest
java.io.IOException: Communication error for url: GET https://bitbucket.examplehttps://bitbucket.example/rest/api/1.0/projects/DEMOrepos/demo/branches?filterText=master&start=0&limit=200 HTTP/1.1
	at com.cloudbees.jenkins.plugins.bitbucket.impl.client.AbstractBitbucketApi.doRequest
	at com.cloudbees.jenkins.plugins.bitbucket.impl.client.AbstractBitbucketApi.getRequest
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getResource
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getSingleBranch
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getBranch
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve
	at jenkins.scm.api.SCMSource.fetch

The problem is that getSingleBranch prepends this.baseURL to the URI
template and calls getResource, which expands the template and
prepends this.baseURL to the resulting URL again.

getResource is called only by getSingleTag and getSingleBranch, and
both of them include the base URL in the template.
Thus, getResource should not prepend it again.